---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 17/07/2020 15:10
---

-- TODO Rework visual wrapper

---@class Visual
Visual = Visual or {};

function Visual.Popup()

end
