---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

print("^1 RageUI - testing file is started. ^0")

RMenu.Add('showcase', 'main', RageUI.CreateMenu("RageUI", "Undefined for using SetSubtitle"))
RMenu:Get('showcase', 'main'):SetSubtitle("~b~RAGEUI SHOWCASE")
RMenu:Get('showcase', 'main').EnableMouse = true
RMenu:Get('showcase', 'main').Closed = function()
    -- TODO Perform action
end;

---@type string
local description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";

local checkbox = false;

local availableActions = { "Action 1", "Action 2" }
local actionIndex = 1

Citizen.CreateThread(function()
    while (true) do
        Citizen.Wait(1.0)

        if IsControlJustPressed(1, 51) then
            RageUI.Visible(RMenu:Get('showcase', 'main'), not RageUI.Visible(RMenu:Get('showcase', 'main')))
        end

        RageUI.IsVisible(RMenu:Get('showcase', 'main'), true, true, true, function()
            --- Items
            RageUI.Checkbox("Add ketchup ?", description, checkbox, { Style = RageUI.CheckboxStyle.Tick }, {
                onHovered = function()

                end,
                onSelected = function(isActive)

                end,
                onActive = function()

                end,
                onChecked = function()
                    checkbox = true;
                end,
                onUnChecked = function()
                    checkbox = false;
                end
            })

            RageUI.Button('Basic Items', description, true, {
                onHovered = function()

                end,
                onSelected = function()

                end,
                onActive = function()

                end,
            })

            RageUI.ButtonWithStyle('Basic Items', description, { RightLabel = "With Style" }, true, {
                onHovered = function()

                end,
                onSelected = function()

                end,
                onActive = function()

                end,
            })

            RageUI.List("Title", availableActions, actionIndex, description, {}, true, {
                onListChange = function(Index, Items)
                    actionIndex = Index
                end,
                onSelected = function(Index, Items)

                end,
                onHovered = function(Index, Items)

                end
            })


        end, function()
            --- Panel
        end)


    end
end)

