---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 19:07
---

print("^1 RageUI - testing file is started. ^0")

RMenu.Add('showcase', 'main', RageUI.CreateMenu("RageUI", "Undefined for using SetSubtitle"))
local showcase = RMenu:Get('showcase', 'main');
showcase:SetSubtitle("~b~RAGEUI SHOWCASE")

showcase:DisplayHeader(true);
showcase:DisplayGlare(true);
showcase:DisplaySubtitle(true);
showcase:DisplayNavigation(true);
showcase:DisplayInstructionalButton(true);

showcase.EnableMouse = true

showcase.Closed = function()
end;

showcase.onIndexChange = function(Index)
    print(Index)
end

Keys.Register('E', 'E', 'Open RageUI Showcase menu default.', function()
    RageUI.Visible(showcase, not RageUI.Visible(showcase))
end)

Citizen.CreateThread(function()
    while (true) do
        Citizen.Wait(1.0)

        RageUI.IsVisible(showcase, function()
            for i = 1, 100 do
                RageUI.Button('Basic Items', nil, true, {
                    onHovered = function()
                    end,
                    onSelected = function()
                    end,
                    onActive = function()
                    end,
                });
            end
        end, function()

        end)


    end
end)

